# fly.toml app configuration file generated for ms-books-orders on 2025-07-04T21:18:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ms-books-orders'
primary_region = 'bog'

[build]
  dockerfile = "Dockerfile"

[env]
  EUREKA_URL            = "https://eureka-server.fly.dev/eureka"
  MYSQLHOST             = "switchyard.proxy.rlwy.net"
  MYSQLPORT             = "14587"
  MYSQLDATABASE         = "booksorders"
  MYSQLUSER             = "root"
  MYSQLPASSWORD         = "bDxtRHQYAdgdEfnowjpnjubJFymcXmsM"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
